swagger: '2.0'
info:
  version: v1
  title: My API
paths:
  /api/Users:
    get:
      tags:
        - Address
      operationId: ApiAddressGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: array
            items:
              $ref: '#/definitions/AddressModel'
    post:
      tags:
        - Address
      operationId: ApiAddressPost
      consumes:
        - application/json
      produces: []
      parameters:
        - name: model
          in: body
          required: false
          schema:
            $ref: '#/definitions/AddressModel'
      responses:
        '200':
          description: Success
        '400':
          description: Bad Request
definitions:
  AddressModel:
    # required:
    #   - firstName
    #   - lastName
    #   - address
    #   - city
    #   - postalCode
    #   - emailAddress
    type: object
    properties:
      foo:
        type: array
        minItems: 3
        maxItems: 10
        items:
          type: string
          minLength: 1
      bars:
        type: array
        minItems: 5
        items:
          type: object
          required:
            - field1
            - field2
          properties:
            field1:
              type: string
              default: 'abc'
              maxLength: 100
              minLength: 1
              pattern: '^[a-zA-Z\''\s]+$'
            field2:
              type: string
              maxLength: 100
              minLength: 5

      # firstName:
      #   maxLength: 100
      #   minLength: 1
      #   pattern: '^[a-zA-Z\''\s]+$'
      #   type: string
      # lastName:
      #   maxLength: 100
      #   minLength: 1
      #   pattern: '^[a-zA-Z\''\s]+$'
      #   type: string
      # address:
      #   minLength: 1
      #   maxLength: 100
      #   pattern: '^[\w\''\s]+$'
      #   type: string
      # address2:
      #   minLength: 1
      #   maxLength: 100
      #   pattern: '^[\w\''\s]+$'
      #   type: string
      # city:
      #   minLength: 1
      #   maxLength: 100
      #   pattern: '^[\w\''\s]+$'
      #   type: string
      # postalCode:
      #   minLength: 4
      #   maxLength: 8
      #   pattern: '^[\w\s]+$'
      #   type: string
      # emailAddress:
      #   format: email
      #   pattern: '^[\w\@\!\#\%\&\''\*\+\-\/\=\?\`\{\|\}\~\.]+$'
      #   type: string
